name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    name: say-hello
    runs-on: ubuntu-latest
    steps:
      - run: 'echo hello students'
  unit-tests:
    name: 'unit tests'
    runs-on: ubuntu-latest
    needs: say-hello
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm i

      - name: Run unit tests
        run: npm t utils
