name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    name: say-hello
    runs-on: ubuntu-latest
    steps:
      - run: 'echo hello students'
  unit-tests:
    name: 'unit tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm i

      - name: Run unit tests
        run: npm t utils

  e2e-tests:
    name: end to end testing
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Use postgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'my_db'
          postgresql user: 'testyMcTesterson'
          postgresql password: 'secretPassword'

      - name: Install Dependencies
        run: npm i

      - name: Run Integreation Tests
        run: PGDATABASE=my_db PGUSER=testyMcTesterson PGPASSWORD=secretPassword npm t app
